spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/pgdb
    username: postgres
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      hbm2ddl.auto: create

server:
  context-path: /uaa
  port: 5000