apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: pocaccesstage/taskmanager-auth-service
        ports:
        - containerPort: 5000
        env:
        - name: CONFIG_SERVICE_PASSWORD 
          value: "senh@" 
        - name: DB_PASS
          value: "@#ACCESSTAG@#"