apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: pocaccesstage/taskmanager-config
        ports:
        - containerPort: 8888
        env:
        - name: CONFIG_SERVICE_PASSWORD 
          value: "senh@"
        - name: DB_PASS
          value: "@#ACCESSTAG@#"