apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-postgres
  labels:
    name: disk-postgres
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "disk-postgres"
    fsType: "ext4"
